### ISSUE TITLE
install issue CLAMAV and Roundcube

### ISSUE THREAD

**Issue by x86fantini** [magenx/magenx-email-server#10]
Hi, on a centos 6 x64 VPS with php 5.4 already installad, during 

"packages" installation i receive

errore durante la lettura delle informazioni sul servizio clamav: No such file or directory
it means (error reading information on service)

and during "roundcube" installation i receive

---> Download and configure ROUNDCUBE 1.1.x? [y/n][n]:y
---> Edit your installation folder full path: /var/www/html/rcb

  ROUNDCUBE will be installed into:
		/var/www/html/rcb

------> Press [Enter] key to continue

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

totale 0

can you please help me?
thank you

**Comment by magenx** [comment]
clamav error can be chkconfig, ignore it. just check if it works later.
roundcube version updated.

**Comment by x86fantini** [comment]
ok i will retry now

**Comment by x86fantini** [comment]
ok instalation went smoth, during config alhtough:

		Import Roundcube database tables...
./mail.sh: line 550: /SQL/mysql.initial.sql: No such file or directory

**Comment by magenx** [comment]
yes, you probably lost ${RCB_PATH} variable. need to manually install.
