### ISSUE TITLE
Problem in Dovecot Service

### ISSUE THREAD

**Issue by corpsysgit** [magenx/magenx-email-server#13]
Hello, thank you for making the script available.

I'm having the following problem with dovecot:

● dovecot.service - Dovecot IMAP / POP3 email server
    Loaded: loaded (/usr/lib/systemd/system/dovecot.service; enabled; vendor pres et: disabled)
    Active: failed (Result: exit-code) since Tue 2017-08-08 17:07:50 UTC; 7 hours ago
      Docs: man: dovecot (1)
            Http://wiki2.dovecot.org/

Aug 08 17:07:50 corpsys systemd [1]: Starting Dovecot IMAP / POP3 email server ...
Aug 08 17:07:50 corpsys dovecot [8354]: doveconf: Fatal: Error in configurat ... ry
Aug 08 17:07:50 corpsys systemd [1]: dovecot.service: control process exited ... 89
Aug 08 17:07:50 corpsys systemd [1]: Failed to start Dovecot IMAP / POP3 email ... r.
Aug 08 17:07:50 corpsys systemd [1]: Unit dovecot.service entered failed state.
Aug 08 17:07:50 corpsys systemd [1]: dovecot.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by magenx** [comment]
could you please extract full error message

**Comment by corpsysgit** [comment]
AFTER COMMAND LINE:  journalctl -xe

-- Subject: Unit service-status-mail@mysqld.service.service has finished start-u
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit service-status-mail@mysqld.service.service has finished starting up.
--
-- The start-up result is done.
Aug 10 23:35:54 corpsys systemd[1]: Starting Service Status Monitor...
-- Subject: Unit service-status-mail@mysqld.service.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit service-status-mail@mysqld.service.service has begun starting up.
Aug 10 23:35:54 corpsys service-status-mail.sh[12934]: sendmail: fatal: root(0):
Aug 10 23:35:54 corpsys postfix/sendmail[12940]: fatal: root(0): Recipient addre
Aug 10 23:35:54 corpsys systemd[1]: service-status-mail@mysqld.service.service:
Aug 10 23:35:54 corpsys systemd[1]: Unit service-status-mail@mysqld.service.serv
Aug 10 23:35:54 corpsys systemd[1]: service-status-mail@mysqld.service.service f
Aug 10 23:35:55 corpsys postfix/pickup[6959]: warning: A46A4DD663: message has b
Aug 10 23:35:55 corpsys postfix/pickup[6959]: A46A4DD663: uid=1000 from=<icorpsy
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: A46A4DD663: message-id=<201708102
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: warning: mysql:/etc/postfix/mysql
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: warning: A46A4DD663: virtual_alia
lines 1701-1723/1723 (END)
-- Subject: Unit service-status-mail@mysqld.service.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit service-status-mail@mysqld.service.service has finished starting up.
--
-- The start-up result is done.
Aug 10 23:35:54 corpsys systemd[1]: Starting Service Status Monitor...
-- Subject: Unit service-status-mail@mysqld.service.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit service-status-mail@mysqld.service.service has begun starting up.
Aug 10 23:35:54 corpsys service-status-mail.sh[12934]: sendmail: fatal: root(0): Recipient addresses must be specified on the command line or via the -t option
Aug 10 23:35:54 corpsys postfix/sendmail[12940]: fatal: root(0): Recipient addresses must be specified on the command line or via the -t option
Aug 10 23:35:54 corpsys systemd[1]: service-status-mail@mysqld.service.service: main process exited, code=exited, status=75/n/a
Aug 10 23:35:54 corpsys systemd[1]: Unit service-status-mail@mysqld.service.service entered failed state.
Aug 10 23:35:54 corpsys systemd[1]: service-status-mail@mysqld.service.service failed.
Aug 10 23:35:55 corpsys postfix/pickup[6959]: warning: A46A4DD663: message has been queued for 2 days
Aug 10 23:35:55 corpsys postfix/pickup[6959]: A46A4DD663: uid=1000 from=<icorpsys>
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: A46A4DD663: message-id=<20170810233555.A46A4DD663@corpsys>
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: warning: mysql:/etc/postfix/mysql/virtual-alias-maps.cf lookup error for "icorpsys@corpsys.com.br"
Aug 10 23:35:55 corpsys postfix/cleanup[3874]: warning: A46A4DD663: virtual_alias_maps map lookup problem for icorpsys@corpsys.com.br -- message not accepted, try again later

**Comment by corpsysgit** [comment]
I have magento 2 running with the other script of yours, after using this email server script started working the emails of Magento 2.

But after a few days it stopped, and I identified it that the dovecot service was not working.

**Comment by corpsysgit** [comment]
I rebooted the server and the services are running normally. Thank you!
