### ISSUE TITLE
Is ssl generated by Letsencrypt directly from the script?

### ISSUE THREAD

**Issue by corpsysgit** [magenx/magenx-email-server#17]
Where do you ask for SSL, am I required to have SSL?

Is it generated by Letsencrypt directly by the script or do I have to manually generate and point the path when the script requests?

**Comment by magenx** [comment]
yes you must have ssl key/cert before installation.
if you dont have, just type any dummy name, install, then update config files:
/etc/postfix/main.cf
/etc/dovecot/dovecot.cf
cert  generate with certbot


thank you
