### ISSUE TITLE
ERROR: PHP PACKAGE IS NOT INSTALLED, Even if I have.

### ISSUE THREAD

**Issue by RoldanLT** [magenx/magenx-email-server#4]
I'm trying to install PHP using variant methods:
OpenLitespeed - http://open.litespeedtech.com/mediawiki/index.php/Help:4_Line_Install
CentminMod - http://centminmod.com/
# php -v
PHP 5.4.39 (cli) (built: Apr 16 2015 18:04:51)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

Both PHP installation works fine, but your script doesn't recognized it.

**Comment by oasisfleeting** [comment]
php.ini
include_path=":/usr/bin/php:/usr/share/pear" ?

**Comment by RoldanLT** [comment]
I hope I can tag @centminmod here.
https://github.com/centminmod/centminmod

**Comment by magenx** [comment]
you are right, php check was pretty simple. in fact centminmod is compiling php ;), these days compiling any packages from webstack is a bit stone-age :)

**Comment by centminmod** [comment]
looks like @magenx added better detection for php version..

compiling PHP has it's advantages, PHP 5.6.8 was just released and only took 90 seconds to update in centmin mod via source compile = no need to wait for distros release :)

    centmin-v1.2.3mod]# php -v
    PHP 5.6.8 (cli) (built: Apr 16 2015 20:44:02) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

@RoldanLT there might be conflicts with what @magenx installs and what Centmin Mod installs so just be aware.

**Comment by magenx** [comment]
compiling a full webstack nowadays is a nonsense,  see when your package has been compiled, and then check rpm release date, it is all the same date :)
http://rpms.famillecollet.com/enterprise/6/php56/x86_64/repoview/
http://rpms.famillecollet.com/enterprise/7/php56/x86_64/repoview/



about mail server script, you are right, this will be rewritten soon, but only to add so features :)
