### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by laapsaap** [magenx/magenx-email-server#6]
Is the centos7 script actually working? I am looking at different config errors.

**Comment by magenx** [comment]
it was installed without errors ,
so what yours exactly

**Comment by laapsaap** [comment]
For example

service imap-login {
        service_count = 1
        process_min_avail = 4
        inet_listener imap {
        port = 0
        }
}


You disabled imap here, so how does roundcube connects to it? Perhaps its because I am missing the roundcube/vimbadmin config files that are not included in the install.

**Comment by magenx** [comment]
is this the only error you have??
```
inet_listener imap {
port = 0
}
```
this is per dovecot official documentation, to disable non-ssl port
