### ISSUE TITLE
postfix3

### ISSUE THREAD

**Issue by danzelziggy** [magenx/magenx-email-server#9]
starting postfix3
postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2015-12-16 17:43:25 PHT; 3s ago
  Process: 2884 ExecStart=/usr/sbin/postfix start (code=exited, status=1/FAILURE)
  Process: 2881 ExecStartPre=/usr/libexec/postfix/chroot-update (code=exited, status=0/SUCCESS)
  Process: 2878 ExecStartPre=/usr/libexec/postfix/aliasesdb (code=exited, status=0/SUCCESS)

Dec 16 17:43:24 localhost.localdomain systemd[1]: Starting Postfix Mail Transport Agent...
Dec 16 17:43:24 localhost.localdomain postfix[2884]: Postfix is running with backwards-compatible default settings
Dec 16 17:43:24 localhost.localdomain postfix[2884]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Dec 16 17:43:24 localhost.localdomain postfix[2884]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Dec 16 17:43:24 localhost.localdomain postfix[2884]: /usr/libexec/postfix/postfix-script: line 74: cd: /usr/share/postfix: No such file or directory
Dec 16 17:43:25 localhost.localdomain postfix/postfix-script[2886]: fatal: no Postfix meta directory /usr/share/postfix!
Dec 16 17:43:25 localhost.localdomain systemd[1]: postfix.service: control process exited, code=exited status=1
Dec 16 17:43:25 localhost.localdomain systemd[1]: Failed to start Postfix Mail Transport Agent.
Dec 16 17:43:25 localhost.localdomain systemd[1]: Unit postfix.service entered failed state.
Dec 16 17:43:25 localhost.localdomain systemd[1]: postfix.service failed.

**Comment by magenx** [comment]
```Dec 16 17:43:25 localhost.localdomain postfix/postfix-script[2886]: fatal: no Postfix meta directory /usr/share/postfix!```

```meta directory /usr/share/postfix```
remove it from main.cf

**Comment by danzelziggy** [comment]
im getting a lot of errors using postfix3 from the new repo:

Dec 17 09:06:57 localhost postfix/smtpd[28527]: error: unsupported dictionary type: mysql
Dec 17 09:06:57 localhost postfix/smtpd[28527]: error: unsupported dictionary type: pcre

**Comment by magenx** [comment]
these modules were missing
```postfix3-mysql postfix3-pcre```

thank you for quick test

**Comment by danzelziggy** [comment]
so what i did is:

reinstall everything using centos7 minimal and using your new script, i got truckload of errors:

Dec 18 00:20:37 localhost postfix/smtpd[9935]: warning: cidr map /etc/postfix/config/mx_access, line 271: bad address pattern: "document.addEventListener('DOMContentLoaded',": skipping this rule
Dec 18 00:20:37 localhost postfix/smtpd[9935]: warning: cidr map /etc/postfix/config/mx_access, line 276: no lookup result: skipping this rule
Dec 18 00:20:37 localhost postfix/smtpd[9935]: connect from localhost[::1]
Dec 18 00:20:37 localhost postfix/trivial-rewrite[9807]: warning: mysql:/etc/postfix/mysql/virtual-alias-maps.cf is unavailable. unsupported dictionary type: mysql
Dec 18 00:20:37 localhost postfix/trivial-rewrite[9807]: warning: virtual_alias_domains: mysql:/etc/postfix/mysql/virtual-alias-maps.cf: table lookup problem
Dec 18 00:20:37 localhost postfix/trivial-rewrite[9807]: warning: virtual_alias_domains lookup failure
Dec 18 00:20:37 localhost postfix/smtpd[9935]: warning: pcre:/etc/postfix/config/white_client_ip is unavailable. unsupported dictionary type: pcre
Dec 18 00:20:37 localhost postfix/smtpd[9935]: warning: pcre:/etc/postfix/config/white_client_ip: table lookup problem
Dec 18 00:20:37 localhost postfix/smtpd[9935]: NOQUEUE: reject: RCPT from localhost[::1]: 451 4.3.5 <localhost[::1]>: Client host rejected: Server configuration error; from=<admin@mailic.com> to=<admin@mailic.com> proto=ESMTP helo=<localhost>
Dec 18 00:20:40 localhost postfix/smtpd[9935]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=0/1 quit=1 commands=3/4
